version: '3'
services:
    project_manager_app:
        build: ./build
        image: atsanna/codeigniter4:latest
        container_name: project_manager_app
        restart: unless-stopped
        volumes:
        - ./build/custom.ini:/usr/local/etc/php/conf.d/whatever.ini
        - ./:/var/www/html
        - ./build/vhost.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - '82:80'
        networks:
            - project-app-network
    project_db:
        image: 'mysql:8.0'
        container_name: project_db
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3301}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/conf.d
            - ./mysql/init:/docker-entrypoint-initdb.d
        networks:
            - project-app-network
    pr_phpmyadmin:
        container_name: pr_phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        restart: unless-stopped
        ports:
            - 8888:80
        environment:
          PMA_USER: '${DB_USERNAME}'
          PMA_PASSWORD: '${DB_PASSWORD}'
          PMA_HOSTS: 'project_db'
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        networks:
            - project-app-network
networks:
  project-app-network:
    driver: bridge